import { createContext } from "react"

type FormContextType = {
    page: number, 
    setPage: (v: number) => void,
    name: string, 
    setName: (v: string) => void,
    document: string,
    setDocument: (v: string) => void,
    dateOfBirth: Date | undefined,
    setDateOfBirth: (v: Date | undefined) => void,
    birthSex: string,
    setBirthSex: (v: string) => void,
    A1a: number | undefined,
    setA1a: (v: number) => void,
    A1b: number | undefined,
    setA1b: (v: number) => void,
    A1c: number | undefined,
    setA1c: (v: number) => void,
    A1d: number | undefined,
    setA1d: (v: number) => void,
    A1e: number | undefined,
    setA1e: (v: number) => void,
    A1f: number | undefined,
    setA1f: (v: number) => void,
    A1g: number | undefined,
    setA1g: (v: number) => void,
    A1h: number | undefined,
    setA1h: (v: number) => void,
    A1i: number | undefined,
    setA1i: (v: number) => void,
    A2a: number | undefined,
    setA2a: (v: number) => void,
    A2b: number | undefined,
    setA2b: (v: number) => void,
    A2c: number | undefined,
    setA2c: (v: number) => void,
    A2d: number | undefined,
    setA2d: (v: number) => void,
    A2e: number | undefined,
    setA2e: (v: number) => void,
    A2f: number | undefined,
    setA2f: (v: number) => void,
    A2g: number | undefined,
    setA2g: (v: number) => void,
    A2h: number | undefined,
    setA2h: (v: number) => void,
    A2i: number | undefined,
    setA2i: (v: number) => void,
    criterionB: boolean | undefined,
    setCriterionB: (v: boolean) => void,
    criterionC: boolean | undefined,
    setCriterionC: (v: boolean) => void,
    criterionD: boolean | undefined,
    setCriterionD: (v: boolean) => void,
    criterionE: boolean | undefined,
    setCriterionE: (v: boolean) => void,
    handleSubmitForm: () => void
}

export const FormContext = createContext<FormContextType>({} as FormContextType); 